### ISSUE TITLE
Figuring out the cutoff frequency?

### ISSUE THREAD

**Issue by kswain1** [danielmurray/adaptiv#1]
How did you figure out the cutoff frequency for your project? I noticed that the communication frequency is at 50hz.

**Comment by danielmurray** [comment]
Howdy Kehlin,
To be honest my method for determining the cutoff frequency was pretty un-scientific. My goal was to build something that worked well at even high pace rates, aka running. I did some minimal research and found the average stride rate for professional runners is around 180 strides a minute, or 3 strides a second or 3hz. The average recreational runner is in the 120 - 150 range, so 3.667 hz is definitely enough to capture the fastest of runners with the tiniest of legs. Hope this helps.
Dan
