### ISSUE TITLE
the equation and the code isn't same?

### ISSUE THREAD

**Issue by ZhouJY0224** [danielmurray/adaptiv#5]
thank for your article, but what is the alpha and beta in the code? i cannot connect with the equations which you gave in this article.

**Comment by danielmurray** [comment]
Howdy,
It's been awhile since I've written this code. Can you tell me which alpha and beta you are referring to?
Thanks,
Dan

**Comment by ZhouJY0224** [comment]
Thank you for your reply :).
1. The alpha and beta in the file  'adaptiveStepJerkThreshold.py'
2. How can I understand the connect between the file 'adaptiveStepJerkThresholdOld.py' and 'adaptiveStepJerkThreshold.py'？ I knew the equations you gave were implemented in file 'adaptiveStepJerkThresholdOld.py'.
3. How can I understand these codes?
**if jerk > jerk_mean - 4 * jerk_dev:
                        jerk_dev = abs(jerk_mean - jerk) * beta + jerk_dev * (1 - beta)
                        jerk_mean = jerk * alpha + jerk_mean * (1 - alpha)**
Thanks.

**Comment by danielmurray** [comment]
I see, yeah, think of alpha and beta as multipliers that help us update the rolling `jerk_mean` and `jerk_dev` values. This way we don't have to keep a buffer of jerk values saved, all we have to do is update the next `jerk_mean` with 12.5% new jerk value and 87.5% the old jerk mean value. Same goes for `jerk_dev`.

Hope this helps,
Dan
